name: test
channels:
  - robostack
  - conda-forge
dependencies:
  # build deps
  - compilers
  - ninja
  - cmake
  - catkin_pkg
  - pkg-config
  # Other deps
  - assimp
  - boost
  - bullet
  - console_bridge
  - eigen
  - orocos-kdl
  - python
  - ros-distro-mutex 0.1 noetic
  - ros-noetic-angles
  - ros-noetic-catkin
  - ros-noetic-eigen-conversions
  - ros-noetic-eigen-stl-containers
  # - ros-noetic-fcl
  - fcl
  - ros-noetic-geometric-shapes
  - ros-noetic-geometry-msgs
  - ros-noetic-kdl-parser
  - ros-noetic-moveit-msgs
  - ros-noetic-moveit-resources-panda-moveit-config
  - ros-noetic-moveit-resources-pr2-description
  - ros-noetic-octomap
  - ros-noetic-octomap-msgs
  - ros-noetic-random-numbers
  - ros-noetic-rosconsole
  - ros-noetic-roslib
  - ros-noetic-rostime
  - ros-noetic-rosunit
  - ros-noetic-sensor-msgs
  - ros-noetic-shape-msgs
  - ros-noetic-srdfdom
  - ros-noetic-std-msgs
  - ros-noetic-tf2-eigen
  - ros-noetic-tf2-geometry-msgs
  - ros-noetic-tf2-kdl
  - ros-noetic-trajectory-msgs
  - ros-noetic-urdf
  - ros-noetic-visualization-msgs
  - ros-noetic-xmlrpcpp
  - ros-noetic-pybind11-catkin
  - urdfdom 1.0.*
  - urdfdom_headers 1.0.*
